version: '3.8'

services:
  web:
    build:
      context: ./backend
    ports:
      - "8000:8000"
    depends_on:
       - postgres
    environment:
      DATABASE_URL: postgres://postgres:postgres@postgres:5432/mydatabase
    command: gunicorn -w 4 -b 0.0.0.0:8000 run:app


  postgres:
    image: postgres
    environment:
      POSTGRES_USER: <<USERID>>
      POSTGRES_PASSWORD: <<PASSWORD>>
      POSTGRES_DB: <<DB_NAME>>
    ports:
      - "5432:5432"

