name: Deploy To Production

on: 
  push:
    branches:
      - main

job:
  build-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set Up Node.js
        uses: actions/setup-node@v2
        with:
          node-version: 14
  # TODO: finish action and deployment setup